### ISSUE TITLE
Padding before colon in struct key/value

### ISSUE THREAD

**Issue by bdw429s** [jcberquist/commandbox-cfformat#13]
Allow this
```js
{
  foo: 'bar'
}
```
to be this
```js
{
  foo : 'bar'
}
```

**Comment by jcberquist** [comment]
So I have changed the `struct.separator` setting to be used exactly as it is specified, provided that it contains only a single `:` or `=` with optional surrounding whitespace and is 3 characters in length or less (otherwise it is ignored). So now you can do `"struct.separator": " : "` and that is what will be used. I am not sure about this approach but it seemed like the easiest way to also support formatting like `{a=1}` and `{a:1}`.

Side note: I think in the future I might add a quick check of user supplied settings and throw an error if any of them are invalid rather than silently ignoring them.

**Comment by bdw429s** [comment]
> Side note: I think in the future I might add a quick check of user supplied settings and throw an error if any of them are invalid rather than silently ignoring them.

Yes, please.  I _hate_ silently ignored settings.  Or at least a warning in the console.

**Comment by jcberquist** [comment]
This is now in `v0.8.0`. Also when an invalid setting name or value is used now, an error will be thrown instead of having that setting be silently ignored.

**Comment by bdw429s** [comment]
Excellent!
