### ISSUE TITLE
preserve case in doc-block?

### ISSUE THREAD

**Issue by softwareCobbler** [jcberquist/commandbox-cfformat#141]
I have some comments in a docblock, where some portions of the comment are forced to lowercase after a cfformat run.

The offenders are always delimited by matching `<>`, like

```
/**
* @attr parameterizedBy<SomeType>
*/
```
becomes
```
/**
* @attr parameterizedBy<sometype>
*/
```
It seems to only lower-case the stuff inside the `<>`.

Is there a flag for this maybe?
Thanks for your time.

**Comment by jcberquist** [comment]
The issue here is that `<SomeType>` in a docblock is being interpreted as an HTML tag - since docblocks often contain HTML for automatic documentation generation, the underlying engine is geared toward identifying that syntax as a tag. Then the `tags.lowercase` setting which defaults to true takes over and lowercases it. I am not sure about the best approach to this overall, but at least you can set `tags.lowercase` to false to prevent this from happening.

**Comment by softwareCobbler** [comment]
ah, parsing as an html tag, that makes sense. thanks!
