### ISSUE TITLE
Automatically use ` .cfformat.json` file if present.

### ISSUE THREAD

**Issue by elpete** [jcberquist/commandbox-cfformat#2]
It would be nice if this module would automatic pass a `.cfformat.json` file (or similar name) if it was present as the `settingsPath`.

(I'd be happy to implement this as a PR if you like it.)

**Comment by jcberquist** [comment]
This is something I have wanted to do, I just haven't figured out how it should look/work. So thank you for suggesting it, as now I can get your input. :) 

Currently, the default settings are used as a base, and then if `cfformat.settings` is set in the CommandBox config settings, that file is loaded and merged onto the base. Finally, if a path to settings is passed into the command, those settings are merged last.

I think a settings file passed inline to the command should win (be merged last), and I presume if the command looks for a settings file by convention (Where? Here I really need input, should it look for a settings file in the directory the command was run from? Should it climb the the directory tree, either from the target file/directory, or the CWD?) that would be used next to last. So I envision the order of settings to be:

1. Base settings
2. Settings file set in CommandBox config (`cfformat.settings` currently)
3. Settings file found by convention based, in some fashion, on where command was run
4. Settings file passed inline to the command

Does this make sense to you?

In addition, for the `cfformat.settings` config setting, I have been thinking about defaulting it to `~/cfformat.json` so you can just create a settings file in your home directory and it will get picked up. (And then of course you could override that location by specifying the config setting explicitly.)

Incidentally, I noticed you suggested `.cfformat.json` - that was honestly my first thought for a settings file name, but really because I see the `.settings.json` used all over the place.  I am inclined to it for that reason, but what is the rational for it?

**Comment by elpete** [comment]
> 1. Base settings
> 2. Settings file set in CommandBox config (`cfformat.settings` currently)
> 3. Settings file found by convention based, in some fashion, on where command was run
> 4. Settings file passed inline to the command

I agree with the order you specified for overriding settings.  This is especially important because it allows a repo to store its format settings.  I as a user can contribute to a repo and any discrepancies in format taste will be decided by the repo.

> In addition, for the `cfformat.settings` config setting, I have been thinking about defaulting it to `~/cfformat.json` so you can just create a settings file in your home directory and it will get picked up. (And then of course you could override that location by specifying the config setting explicitly.)

I think you have this covered with the CommandBox config setting.

> Incidentally, I noticed you suggested `.cfformat.json` - that was honestly my first thought for a settings file name, but really because I see the `.settings.json` used all over the place. I am inclined to it for that reason, but what is the rational for it?

It seems to be the standard for configuration files in a repo to begin with a period (`.`).  I was just following this convention.

**Comment by jcberquist** [comment]
I have added support for this. Let me know how it goes!
