### ISSUE TITLE
reference link on forgebox is 404 

### ISSUE THREAD

**Issue by zspitzer** [jcberquist/commandbox-cfformat#22]
https://www.forgebox.io/view/commandbox-cfformat

the reference link points to https://www.forgebox.io/reference.md

**Comment by jcberquist** [comment]
I used a relative link for GitHub. I guess that causes problems when ForgeBox copies the readme.

**Comment by bdw429s** [comment]
The fix is probably to provide a full link in the markdown.  I can create a forgebox ticket to see if there's a way we can try and "fix" relative links in the description.  The biggest issue is we don't know the original context of the readme file.  i.e., did it come from Github, Bitbucket, Github enterprise, etc so there's no reliable way to know where the relative link would have originally pointed once the markdown has been imported into ForgeBox.

**Comment by jcberquist** [comment]
Alright, it is now a full link so this should be resolved - I guess it will be fully resolved when I publish another version to ForgeBox?

**Comment by bdw429s** [comment]
yep you don't need to bump the version, just rerun the `publish` command and it will update the description with the current readme.

**Comment by jcberquist** [comment]
@bdw429s That was easy, thanks!
