### ISSUE TITLE
Case options for UDF vs native functions

### ISSUE THREAD

**Issue by valetservice** [jcberquist/commandbox-cfformat#33]
It would be great to configure function case separately for native functions and user defined functions.

One code standard I have observed is that native cfml functions are `PascalCase` and user defined functions are `camelCase`.

Eg:
```
"function_call.native.case":"PascalCase" -- or "Upper / Lower"
"function_call.user_defined.case":"camelCase"

```
Input:
```
today = now();
earlier = OneDayAgo();
```

Output:
```
today = Now();
earlier = oneDayAgo();
```

Thanks again for a great extenstion!

**Comment by jcberquist** [comment]
I currently use the list of functions [here](https://github.com/jcberquist/commandbox-cfformat/blob/master/data/functions.json) to format/case built-in functions. I took this list from the [cfdocs.org](https://cfdocs.org) data available in the GitHub [repo](https://github.com/foundeo/cfdocs). Though I would like to keep this specific formatting as the default, it seems reasonable to me to add alternate casings for built-in functions (in this case I guess the alternate would be Pascal since currently cfdocs choose to lowercase the first word). 

I am less sure about user defined functions since I think the best I could do there is upper/lower case the first letter - ensuring doing that makes sense in context seems like it could be a lot of work. If the setting were limited to the capitalization of the first letter, regardless of how the rest of the function call was cased, would you still be interested in it?

**Comment by valetservice** [comment]
Hi John, yes the first character was all I had in mind.. This would be a great addition. Thanks!

**Comment by jcberquist** [comment]
This has been added to `v0.12.0`.

**Comment by chapmandu** [comment]
Gold! This is a game changing upgrade.. Kudos!
