### ISSUE TITLE
Unwanted line breaks in function string arguments 

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/commandbox-cfformat#39]
Input:
```
qry = querySim("
	id , fk_id , create_date
	1 | 3 | #Now()#
	2 | 4 | -
");
```
Output:
```
qry = querySim(
	"
	id , fk_id , create_date
	1 | 3 | #Now()#
	2 | 4 | -
"
);
```
Expected:
```
qry = querySim("
	id , fk_id , create_date
	1 | 3 | #Now()#
	2 | 4 | -
");
```

**Comment by jcberquist** [comment]
So with this situation the issue is that the string contents have to be preserved - so when the string is formatted, the line indents inside the string have to be kept the same. That, combined with the logic that prints multiline function arguments produces the output you reference. 

If you indent the output yourself, you will see that indent will be preserved as well, e.g.:
```cfc
qry = querySim(
    "
        id , fk_id , create_date
        1 | 3 | #Now()#
        2 | 4 | -
    "
);
```
If the above is formatted, the input and output will match.

I see that your specific request is not to put line breaks before and after the quotes in this situation - however, I am not sure how that would work in all such function call strings, and I checked what prettier does and it matches the current cfformat output, so I think at least for now I am not inclined to change this behavior.

**Comment by chapmandu** [comment]
All good. Thanks for reviewing.
