### ISSUE TITLE
Breaks not respected on component declarations

### ISSUE THREAD

**Issue by lmajano** [jcberquist/commandbox-cfformat#55]
I currently have a component declration like so:

![image](https://user-images.githubusercontent.com/137111/73573338-bdb78600-4438-11ea-851a-76a50e186b9c.png)

```
component 
	extends="coldbox.system.testing.BaseModelTest" 
	model="cbvalidation.models.validators.MethodValidator" 
{
```

I would have expected for the formmater to respect the breaks.  However, it does this:

```
component extends="coldbox.system.testing.BaseModelTest" model="cbvalidation.models.validators.MethodValidator" {
```

Here are my rules

```
{
	"array.empty_padding": false,
	"array.padding": true,
	"array.multiline.min_length": 40,
	"array.multiline.element_count": 4,
	"array.multiline.leading_comma.padding": true,
	"array.multiline.leading_comma": false,
	"alignment.consecutive.assignments": true,
	"alignment.consecutive.properties": true,
	"alignment.consecutive.params": true,
	"brackets.padding": true,
	"comment.asterisks": "align",
	"binary_operators.padding": true,
	"for_loop_semicolons.padding": true,
	"function_call.empty_padding": false,
	"function_call.padding": true,
	"function_call.multiline.leading_comma.padding": true,
	"function_call.casing.builtin": "cfdocs",
	"function_call.casing.userdefined": "camel",
	"function_call.multiline.element_count": 4,
	"function_call.multiline.leading_comma": false,
	"function_call.multiline.min_length": 40,
	"function_declaration.padding": true,
	"function_declaration.empty_padding": false,
	"function_declaration.multiline.leading_comma": false,
	"function_declaration.multiline.leading_comma.padding": true,
	"function_declaration.multiline.element_count": 4,
	"function_declaration.multiline.min_length": 40,
	"function_declaration.group_to_block_spacing": "compact",
	"function_anonymous.empty_padding": false,
	"function_anonymous.group_to_block_spacing": "compact",
	"function_anonymous.multiline.element_count": 4,
	"function_anonymous.multiline.leading_comma": false,
	"function_anonymous.multiline.leading_comma.padding": true,
	"function_anonymous.multiline.min_length": 40,
	"function_anonymous.padding": true,
	"indent_size": 4,
	"keywords.block_to_keyword_spacing": "spaced",
	"keywords.group_to_block_spacing": "spaced",
	"keywords.padding_inside_group": true,
	"keywords.spacing_to_block": "spaced",
	"keywords.spacing_to_group": true,
	"keywords.empty_group_spacing": false,
	"max_columns": 120,
	"parentheses.padding": true,
	"strings.quote": "double",
	"strings.attributes.quote": "double",
	"struct.separator": " : ",
	"struct.padding": true,
	"struct.empty_padding": false,
	"struct.multiline.leading_comma": false,
	"struct.multiline.leading_comma.padding": true,
	"struct.multiline.element_count": 4,
	"struct.multiline.min_length": 40,
	"tab_indent": true
}

**Comment by jcberquist** [comment]
As it stands right now, component attributes are printed on one line if they fit in the `max_columns` setting, and are otherwise printed on multiple lines.

I did change the behavior for component properties back when addressing #50 so that a new line break after `property` would be preserved and cause all attributes to be printed on subsequent lines, so I get that is now that is inconsistent with the behavior here. I can tweak one or the other so that they match up. 

I am torn about this, since if I start preserving tag attribute line breaks here as well, then I start to wonder if I need to preserve them in all cases where they are present in the source. Doing that feels a little opposed to what I want to do with this library. Maybe a setting is needed instead.

@elpete do you have any thoughts on this?

**Comment by elpete** [comment]
Hey, @lmajano. I think your problem here would be solved by decreasing your `max_columns` property in your settings. I recommend setting it to whatever ruler you have showing in your editor. I find that my code “looks right” if it is inside that line, regardless of where it is. 

As far as respecting line breaks, it doesn’t make much sense for a formatting library to ignore line breaks mostly because we can’t know if it was intentional or coincidental or even accidental. The best thing to do will be to adjust the current settings. 

That said, @jcberquist — I think both parameters and maybe even component / function metadata could use a few new settings like so:

```json
{
    "property_attributes.multiline.element_count": 4,
    "property_attributes.multiline.min_length": 40,
    "metadata.multiline.element_count": 4,
    "metadata.multiline.min_length": 40
}
```

You could split up the metadata ones between component metadata and function metadata as well, I suppose. 

Hope that helps!

**Comment by jcberquist** [comment]
Thanks for the input @elpete! I agree with this:
> As far as respecting line breaks, it doesn’t make much sense for a formatting library to ignore line breaks mostly because we can’t know if it was intentional or coincidental or even accidental.

I think I made a mistake back in #50 when I added the logic to look for line breaks in property tags. I am going to remove that.  The `max_columns` setting should be used to control when these print on one line or multiple lines, and not whether or not there are line breaks in the source. 

That said, I will also add settings as suggested above to give more control over the output, without relying on how the input looks.

**Comment by jcberquist** [comment]
`v0.13.5` has the new settings, hopefully that gives you the output you want.

**Comment by lmajano** [comment]
Thanks @jcberquist so in summary, what are the new settings that are introduced?

**Comment by jcberquist** [comment]
@lmajano You can see them in the commit message above, they are:
```
"metadata.multiline.element_count": 4
"metadata.multiline.min_length": 40
"property.multiline.element_count": 4
"property.multiline.min_length": 40
```
The first two will affect component attributes/metadata, and the last two will affect property attributes.
