### ISSUE TITLE
Formatter breaks on some blocked comments

### ISSUE THREAD

**Issue by rbreaves** [jcberquist/commandbox-cfformat#97]
Not a hard break or anything it just ignores the comment block if it is not what it expects I suppose.

If there is any asterisks lacking in a comment block instead of correcting it it completely ignores the block thus proper indentation will not be applied.

```
{
    /**
      a comment
     */
}
```

That's still a valid comment, but the cfformatter won't touch it.

**Comment by jcberquist** [comment]
If I understand your issue correctly, this is expected behavior. By default, `cfformat` checks block comments to see if all lines begin with a `*`, and if so, aligns them (see [reference.md#commentasterisks](https://github.com/jcberquist/commandbox-cfformat/blob/master/reference.md#commentasterisks)). Otherwise, it preserves the indent levels of the comment (similar to the contents of strings).

**Comment by rbreaves** [comment]
Yea, this may be more of a thing for cflinter to help resolve now that I think about it. I will close this ticket.
